name: Backend Pipeline

on:
  pull_request:
    branches: [ "dev", "main" ]
    paths:
      - 'src/**'
      - 'api/**'
      - 'package.json'
      - 'server.js'

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with: { node-version: '20', cache: 'pnpm' }
      
      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint
      - run: pnpm run test
        env:
          MONGO: ${{ secrets.MONGO }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          DODO_TOKEN: ${{ secrets.DODO_TOKEN }}
          DODO_WEBHOOK_TOKEN: ${{ secrets.DODO_WEBHOOK_TOKEN }}
          FRONTEND_ORIGIN: ${{ secrets.FRONTEND_ORIGIN }}
          PRODUCT_ID: ${{ secrets.PRODUCT_ID }}